name: Build and publish F-Droid pre-release debug APK

on:
  # Trigger by pushing a version tag (which are protected)
  push:
    tags:
      - v*.*.*-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish-prerelease-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Generate F-Droid debug APK
        run: ./gradlew assembleFdroidDebug --stacktrace

      - name: Publish APK as a Github pre-release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: '**/*.apk'
          prerelease: true