name: Build and publish pre-release debug APK

on:
  # Trigger by pushing a version tag (which are protected)
  push:
    tags:
      - v*.*.*-*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish-prerelease-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Generate debug APK
        run: ./gradlew assemblePremiumDebug --stacktrace

      - name: Get version name from git tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Rename APK file
        run: mv app/build/outputs/apk/premium/debug/app-premium-debug.apk orgzly-revived-${{ env.VERSION }}-debug.apk

      - name: Publish APK as a Github pre-release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: '*.apk'
          prerelease: true
          draft: true
