name: Create APK signing secrets

on:
  workflow_dispatch:

jobs:
  create-apk-signing-secrets:
    runs-on: ubuntu-latest
    steps:

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate key store password and store as env variable
        run: |
          secret=$(dd bs=256 status=none if=/dev/urandom count=1 | tr -dc "a-zA-Z0-9")
          echo "PASSWORD=$secret" >> "$GITHUB_ENV"

      - name: Store key store password as repository secret
        uses: action-pack/set-secret@v1
        with:
          name: 'APK_SIGNING_KEYSTORE_PASSWORD'
          value: "${{ env.PASSWORD }}"
          token: ${{ secrets.SECRETS_CREATION_TOKEN }}

      - name: Create key store for APK signing
        id: create_keystore
        run: |
          keytool -genkeypair -keystore temp.jks -alias mykey -keyalg RSA -keysize 4096 -validity 10000 -dname "cn=Orgzly Revived Developers o=Orgzly Community" -storepass:env PASSWORD -keypass:env PASSWORD
          echo "keystore=$(openssl base64 < temp.jks | tr -d '\n')" >> "$GITHUB_OUTPUT"

      - name: Store key store file as repository secret
        uses: action-pack/set-secret@v1
        with:
          name: 'APK_SIGNING_KEYSTORE_FILE'
          value: "${{steps.create_keystore.outputs.keystore}}"
          token: ${{ secrets.SECRETS_CREATION_TOKEN }}
