name: Build and release

on:
  # Trigger by pushing a version tag (which are protected)
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-and-release-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for app release
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Generate release APK
        run: ./gradlew assemblePremiumRelease --stacktrace

      - name: Sign APK with keystore
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/premium/release
          signingKeyBase64: ${{ secrets.RELEASE_SIGNING_KEY_STORE }}
          alias: key0
          keyStorePassword: ${{ secrets.KEY_STORE_PASS }}
          keyPassword: ${{ secrets.KEY_STORE_PASS }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: orgzly-revived-premium-release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Echo APK name
        run: echo Signed APK file ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Release signed APK
        uses: MicahSphelele/action-publish-signed-apk@main
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_CREATION_TOKEN }}
          APP_FOLDER: app
          FILE_DIR: ${{steps.sign_app.outputs.signedReleaseFile}}
